version: "3.4"
services: 
 mysql: 
   image: mysql
   ports: 
   - 3306:3306
   volumes: 
   - /home/majie/桌面/docker_lib/mysql:/var/lib/mysql
   environment: 
   - MYSQL_ROOT_PASSWORD=123456
   command: 
    --default-authentication-plugin=mysql_native_password
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_general_ci
    --explicit_defaults_for_timestamp=true
    --lower_case_table_names=1
    --max_allowed_packet=128M;

 phpmyadmin: 
   image: phpmyadmin/phpmyadmin
   ports: 
   - 8000:80
   environment: 
   - PMA_ARBITRARY=1
   restart: always
 nginx: 
   image: nginx:alpine
   ports: 
   - 80:80
   volumes: 
   - /home/majie/桌面/docker_html:/usr/share/nginx/html
   - /home/majie/桌面/docker_etc/default.conf:/etc/nginx/conf.d/default.conf
   - /home/majie/桌面/docker_etc/nginx.conf:/etc/nginx/nginx.conf
 php: 
   image: devilbox/php-fpm:7.4-work
   volumes: 
   - /home/majie/桌面/docker_html:/var/www/html
   - /home/majie/桌面/docker_etc/php:/usr/local/etc/php
 